apiVersion: v1
kind: Secret
metadata:
  name: vehicle-catalog-secret
  namespace: vehicle-platform
type: Opaque
stringData:
  DATABASE_URL: postgresql://catalog_user:catalog_password@postgres-catalog:5432/catalog_db
  WEBHOOK_TOKEN: replace-me
  INTERNAL_SERVICE_TOKEN: replace-me-internal
